sudo: false
language: ruby
cache: bundler
rvm:
- 2.0
- 2.1
- 2.2
matrix:
  include:
    - # GitHub Pages
      rvm: 2.3.1
      env: JEKYLL_VERSION=3.3.0
env:
  matrix:
    - JEKYLL_VERSION=3.3
branches:
  only:
    - master
install:
- travis_retry script/bootstrap
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
